apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "bte.fullname" . }}-secret
  labels:
    {{- include "bte.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "secrets/*-secret").AsConfig | nindent 2 }}
