apiVersion: v1
kind: Service
metadata:
  name: {{ include "bte.fullname" . }}
  labels:
    {{- include "bte.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "bte.selectorLabels" . | nindent 4 }}
