name: deploy to dev server with git ref

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
    branches:
        - development

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_DEV }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY_DEV }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/opt/biothings_explorer
          git fetch
          git reset ${{ github.event.inputs.git-ref }}
          cp docker-compose-dev.yml docker-compose.yml
          docker-compose up --force-recreate --build -d
          docker image prune -f

          # alternative way to start the app:
          # npm i --production
          # pm2 restart all
