name: deploy to dev server

on:
  pull_request:
    branches:
      - development
    types: [ closed ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_DEV }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY_DEV }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/opt/biothings_explorer
          rm docker-compose.yml
          git stash
          git pull
          cp docker-compose-dev.yml docker-compose.yml
          docker-compose up --force-recreate --build -d
          docker image prune -f

  performance-test:
    needs: [deploy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: run performance test
      working-directory: ./performance-test
      run: |
        pwd
        npm i -g artillery
        ls -l
        artillery run -e dev --output report_dev.json --config config.yaml scenarios/query.yaml
        artillery report --output report.html report_dev.json
        ls -l
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST_DEV }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY_DEV }}
        port: ${{ secrets.SSH_PORT }}
        source: "performance-test/report.html"
        target: "opt/biothings_explorer/performance-test"
        strip_components: 1
